<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE trilang [
<!ELEMENT trilang (comment|sample)*>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT sample (#PCDATA)>
]>
<trilang>
  <comment>
  9term に付属する UTF サンプルファイルを XML 化しました。
  </comment>
  <comment>
  Here's a sample file of cyrillic, japanese, and greek text:
  </comment>
  <sample>
		Final examination --  Slavic B
			(Time: Three Hours)

Part 1: Translate into English:

	Я стал бывать у Волчаниных.  Обыкновенно
я сидел на нижней ступени террасы; меня томило
недовольство собой, было жаль своей жизни, которая
протекала так быстро и неинтерсно,
и я все думал о том, как хорошо было бы
вырвать из своей груди сердце, которое стало
у меня тяжелым.  А в это время на террасе говорили,
слышался шорох платьев, перелистывали книгу....
  </sample>
  <sample>
	Some Japanese text:

横山さん--

新年明けましておめでとうございます。

久しぶりですね。お元気ですか。お手紙をどもう
ありがとございます。日本語クラスに出します。

十二月は大変忙しかったですから，クラスが
あまりではありませんでした。来月はもっと
暇でしょう。

では，また。さよなら。

	-- ブライアン
  </sample>
  <sample>
	Πρόλογος

  Από τον καιρό που δημοσιεΰετηκε το The C Programming Language το 1978,
ο κόσμος των υπολογιστών έχει υποστεί επαναστατικές αλλαγές.
Οι μεγάλοι υπολογιστές είναι τώρα πολΰ μεγαλΰτεροι, και οι προσωπικοί
υπολογιστέσ έχουν ικανότητες που θα ζήλευαν οι και η C, αν και όχι
σημαντικά, και εξαμπλώθηκε πολΰ πιο πέρα από τις ρίζες της ωσ γλώσσας
προγραμματισμοΰ του λειτυπγικοΰ συστήματος UNIX.
  </sample>
</trilang>
